server:
  port: 8080

app:
  jwt:
    secret: "secret"  #weak
    # algorithm: "HC256"  #weak можно убрать, объявоение в jwtprop
    expiration-seconds: 3600
    issuer: gaechka-auth-service
  forwarding:
    url: ""
